apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: scalaway/identityservice:java-maven
          imagePullPolicy: Always
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: identity-service
spec:
  type: ClusterIP
  ports:
    - name: identity-service
      port: 8090
  selector:
    app: identity-service